# Generated by Django 5.1 on 2026-09-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expense_category_income"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Budget",
        ),
    ]
