# Generated by Django 5.1 on 2026-03-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_debt_paymentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food & Dining', 'Food & Dining'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Housing', 'Housing'), ('Education', 'Education'), ('Gym & Fitness', 'Gym & Fitness'), ('Subscriptions', 'Subscriptions'), ('Insurance', 'Insurance'), ('Clothing & Shopping', 'Clothing & Shopping'), ('Personal Care & Beauty', 'Personal Care & Beauty'), ('Gifts & Donations', 'Gifts & Donations'), ('Bills & Utilities', 'Bills & Utilities'), ('Medical & Health', 'Medical & Health'), ('Education & Books', 'Education & Books'), ('Abroad Expense', 'Abroad Expense'), ('Other', 'Other'), ('Immigration', 'Immigration')], max_length=50),
        ),
    ]
