# Generated by Django 5.1 on 2026-05-12 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaycheckConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_pay_date', models.DateField()),
                ('biweekly_amount', models.DecimalField(decimal_places=2, default=1100, max_digits=10)),
                ('second_job_day', models.PositiveSmallIntegerField(default=20)),
                ('second_job_amount', models.DecimalField(decimal_places=2, default=625, max_digits=10)),
                ('second_job_tips', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('extra_payment', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paycheck_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
