# Generated by Django 5.1 on 2026-09-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_planner", "0002_paycheckconfig"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="paycheckallocation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="paycheckallocation",
            name="monthly_plan",
        ),
        migrations.RemoveField(
            model_name="checklistitem",
            name="paycheck_allocation",
        ),
        migrations.RemoveField(
            model_name="paycheckconfig",
            name="user",
        ),
        migrations.RemoveField(
            model_name="monthlyplan",
            name="biweekly_income",
        ),
        migrations.RemoveField(
            model_name="monthlyplan",
            name="is_three_paycheck_month",
        ),
        migrations.RemoveField(
            model_name="monthlyplan",
            name="num_paychecks",
        ),
        migrations.RemoveField(
            model_name="monthlyplan",
            name="second_job_income",
        ),
        migrations.DeleteModel(
            name="MonthlyDebtSnapshot",
        ),
        migrations.DeleteModel(
            name="PaycheckAllocation",
        ),
        migrations.DeleteModel(
            name="PaycheckConfig",
        ),
    ]
