# Generated by Django 5.1 on 2026-10-05 17:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planner', '0003_alter_paycheckallocation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('fixed_expense', 'Fixed Expense'), ('temp_payment', 'Temporary Payment'), ('auto_debit', 'Auto Debit'), ('transfer', 'Transfer'), ('income', 'Income')], default='fixed_expense', max_length=20)),
                ('is_auto_debit', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_day', 'label'],
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='recurring_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='financial_planner.recurringitem'),
        ),
    ]
